### ISSUE TITLE
/DIR1/DIR2/file.txt won't match glob /DIR1/*/*

### ISSUE THREAD

**Issue by PeAb** [dazinator/DotNet.Glob#21] opened 2017-03-06 17:01 UTC
Code example:

```csharp
Glob glob = Glob.Parse(@"/DIR1/*/*");
MatchInfo matchInfo = glob.Match(@"/DIR1/DIR2/file.txt");
Console.Out.WriteLine("matchInfo.Success = {0}", matchInfo.Success);
```

gives:
matchInfo.Success = False

**Comment by dazinator** [comment] 2017-03-06 17:57
Thanks for reporting.
The algortihms for IsMatch and Match are slightly different. Basically because Match() attempts to get additional information and so it does additional analysis, where as IsMatch() always attempts to fail fast if things don't match. 
I'll need to check if this is a problem just for Match() or if it also effects IsMatch. I'll add a couple of tests cases for this.

**Comment by dazinator** [comment] 2017-03-06 18:47
Ok, this is fixed in [latest build](https://ci.appveyor.com/project/dazinator/dotnet-glob/branch/develop)
I have extended the tests a bit, and included this as a regression test.
Latest nuget package if you want to re-test is: https://www.nuget.org/packages/DotNet.Glob/1.5.0-unstable0014

Thanks

**Comment by PeAb** [comment] 2017-03-07 13:24
Thanks, that fixed it. Although in the testcase below:

Glob glob = Glob.Parse(@"/DIR1/ab*d.txt");
string s = @"/DIR1/ab.txt";
bool isMatch = glob.IsMatch(s);
Console.Out.WriteLine("isMatch = {0}", isMatch);
MatchInfo matchInfo = glob.Match(s);
Console.Out.WriteLine("matchInfo.Success = {0}", matchInfo.Success);

The results are:
glob.IsMatch(s) works and returns False
...but glob.Match(s) generates a System.IndexOutOfRangeException

**Comment by dazinator** [comment] 2017-03-07 19:37
Ok thanks, I'll add that to the test cases and will fix that shortly.

**Comment by dazinator** [comment] 2017-03-27 13:48
Just wondering, do you actually need Match() as opposed to IsMatch() ?

I ask because I'm tempted to drop this method until it can be written in a way that ensure it behaves identically to IsMatch.

**Comment by PeAb** [comment] 2017-03-28 09:11
I really only use IsMatch() currently.

**Comment by dazinator** [comment] 2017-05-31 09:52
Closing this, will open a new issue to get rid of Match().

**Closed by dazinator** 2017-05-31 09:52 UTC
